// Code generated by hertz generator.

package v1

import (
	"context"
	v1 "video-platform/biz/model/api/video/v1"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// VideoLikeAction .
// @router /api/v1/interaction/like [POST]
func VideoLikeAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.VideoLikeActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(v1.VideoLikeActionResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListLikedVideos .
// @router /api/v1/interaction/like/list [GET]
func ListLikedVideos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.ListLikedVideosRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(v1.ListLikedVideosResponse)

	c.JSON(consts.StatusOK, resp)
}

// PublishComment .
// @router /api/v1/interaction/comment [POST]
func PublishComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.PublishCommentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(v1.PublishCommentResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListUserComments .
// @router /api/v1/interaction/comment/list [GET]
func ListUserComments(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.ListUserCommentsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(v1.ListUserCommentsResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteComment .
// @router /api/v1/interaction/comment/delete [POST]
func DeleteComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.DeleteCommentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(v1.DeleteCommentResponse)

	c.JSON(consts.StatusOK, resp)
}
