// Code generated by hertz generator.

package v1

import (
	"context"
	v1 "video-platform/biz/model/api/video/v1"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// RelationAction .
// @router /api/v1/relation/action [POST]
func RelationAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.RelationActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(v1.RelationActionResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListFollowings .
// @router /api/v1/relation/following/list [GET]
func ListFollowings(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.ListFollowingsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(v1.ListFollowingsResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListFollowers .
// @router /api/v1/relation/follower/list [GET]
func ListFollowers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.ListFollowersRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(v1.ListFollowersResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListFriends .
// @router /api/v1/relation/friend/list [GET]
func ListFriends(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.ListFriendsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(v1.ListFriendsResponse)

	c.JSON(consts.StatusOK, resp)
}
