// Code generated by hertz generator.

package v1

import (
	"context"
	v1 "video-platform/biz/model/api/video/v1"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// PublishVideo .
// @router /api/v1/video/publish [POST]
func PublishVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.PublishVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(v1.PublishVideoResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListPublishedVideos .
// @router /api/v1/video/list [GET]
func ListPublishedVideos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.ListPublishedVideosRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(v1.ListPublishedVideosResponse)

	c.JSON(consts.StatusOK, resp)
}

// SearchVideos .
// @router /api/v1/video/search [GET]
func SearchVideos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.SearchVideosRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(v1.SearchVideosResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListVideoComments .
// @router /api/v1/video/comments [GET]
func ListVideoComments(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.ListVideoCommentsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(v1.ListVideoCommentsResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetHotVideos .
// @router /api/v1/video/hot [GET]
func GetHotVideos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req v1.GetHotVideosRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(v1.GetHotVideosResponse)

	c.JSON(consts.StatusOK, resp)
}
