// Code generated by hertz generator.

package main

import (
	"log"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"
	"github.com/joho/godotenv"
	"video-platform/biz/dal"
	"video-platform/pkg/storage"
	"video-platform/swagger"
)

func main() {
	// 加载 .env 配置文件
	if err := godotenv.Load(); err != nil {
		log.Println("未找到 .env 文件，将使用系统环境变量")
	}

	// 初始化数据访问层（MySQL + Redis）
	dal.Init()

	h := server.Default()
	h.Use(cors.Default())

	register(h)

	// 挂载静态文件目录（头像、视频）
	storage.BindStatic(h)

	// 绑定 Swagger UI，访问 /swagger/index.html 查看接口文档
	swagger.BindSwagger(h)

	h.Spin()
}
