// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	v1 "video-platform/biz/router/v1"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	v1.RegisterUser(r)
	v1.RegisterVideo(r)
	v1.RegisterInteraction(r)
	v1.RegisterRelation(r)
}
